language: node_js
node_js: stable
sudo: required

services:
  - mongodb

install:
  - npm install
  # - python3 -m pip install Scrapy

  

script:
  - cd finance_spider
  - sh start.sh
  - sleep 20
  - sh stop.sh
  - cd ../finance_web 
  - npm start
