language: node_js
node_js: stable
sudo: false

install:
  - npm install
  # - apt install python3
  # - apt-get install mongodb
  

script:
  - npm start

after_script:
  - cd ./Demo Image
  - git init
  - git config user.name "BarackO"
  - git config user.email "yanghongliu2013@outlook.com"
  - git add .
  - git commit -m "Update demo image"
  - git push --force --quiet "https://${GithubToken}@${GH_REF}" master:master
  
env:
 global:
   - GH_REF: github.com/BarackO/Software-Innovation.git


