language: node_js
sudo: required
node_js: stable
python:
- '2.7'

services:
- mongodb

install:
- cd finance_web
- npm install
- cd ../finance_spider
- sudo pip install -r requiremnets.txt
- sudo pip install pyopenssl --upgrade
- cd ..

script:
- cd finance_spider
- sh start.sh
- sleep 20
- sh stop.sh
- python -m unittest test
- cd ../finance_web
- npm start &
- sleep 20
- npm stop
- rm package-lock.json
- cd ..

deploy:
  provider: script
  skip_cleanup: true
  script: sh deploy.sh
  on:
    branch: master


