language: node_js
sudo: required
node_js: stable
python: 
  - "3.4"

services:
  - mongodb

install:
  - cd finance_web
  - npm install
  - cd ../finance_spider
  - sudo pip install -r requiremnets.txt
  # - sudo pip install pyopenssl --user --upgrade
  - cd ..

  

script:
  - cd finance_spider
  - sh start.sh
  - sleep 20
  - sh stop.sh
  - cd ../finance_web 
  - npm start
