language: node_js
sudo: required
node_js: stable
python:
- '2.7'

services:
- mongodb

addons:
  apt:
    packages:
    - sshpass
install:
- cd finance_web
- npm install
- cd ../finance_spider
- sudo pip install -r requiremnets.txt
- sudo pip install pyopenssl --upgrade
- cd ..

script:
- cd finance_spider
- sh start.sh
- sleep 20
- sh stop.sh
- python -m unittest test
- cd ../finance_web
- npm test
- npm start &
- sleep 20
- npm stop
- rm package-lock.json
- cd ..
- echo "=====begin to deploy====="
- sshpass -p "dplsPublic12" ssh -o StrictHostKeyChecking=no zzm@218.193.183.164 'bash -s' < deploy.sh &
- sleep 60
- echo "=====deploy finished====="
