language: node_js
node_js: stable
sudo: required

install:
  - npm install
  # - python3 -m pip install Scrapy

  

script:
  # - cd finance_spider
  # - . start.sh
  - cd ../finance_web 
  - npm start

  
env:
 global:
   - GH_REF: github.com/BarackO/Software-Innovation.git


